name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  deploy:
    env:
      VERSION: '7.1.1'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: azure/container-actions/docker-login@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker build . -t deciphernow/logstash-oss:${VERSION}
          docker push deciphernow/logstash-oss:${VERSION}
